# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8e97eedc17d94f2957886501942cd44af42e3dd2e82fca2e001e265ab671abd5b7cda8503774ac5b6527eb754cf769940f70528bd4a6345cfd4670229e68ae6

test:
  secret_key_base: 73173f20537ec9b0c36216e61a33513414db90ff36d2b516ab74125821a0bebd5c61d971fac5cfee02658a17c64ae057cf297bd274f9a56523781f291332fa36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
